name: CI

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}


on:
  push:
    branches:
      - review18
  pull_request:
    branches:
      - review18
      - main

jobs: 
    build-and-publish-latest:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4 # Checking out the repo
        - name: Log in to the Container registry
          uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
          with:
            registry: ${{ env.REGISTRY }}
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}


        - name: Extract metadata (tags, labels) for Docker
          id: meta
          uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
          with:
            images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

        - name: Build and push Backend Docker image
          uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
          with:
            context: ./backend
            file: ./backend/Dockerfile
            push: true
            tags: ${{ env.REGISTRY }}/${{ github.repository }}/backend:latest
            labels: ${{ steps.meta.outputs.labels }} 

        - name: Build and push Front Docker image
          uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
          with:
            context: ./frontend
            file: ./frontend/Dockerfile
            push: true
            tags: ${{ env.REGISTRY }}/${{ github.repository }}/frontend:latest
            labels: ${{ steps.meta.outputs.labels }} 



            # - name: Login to GitHub Container Registry
            #   uses: docker/login-action@v3
            #   with:
            #     registry: ghcr.io
            #     username: ${{ github.actor }}
            #     password: ${{ secrets.GITHUB_TOKEN }}

            # - name: Setup Buildx
            #   uses: docker/setup-buildx-action@v3

            # - name: Frontend image
            #   uses: docker/build-push-action@v3
            #   with:
            #     context: ./frontend
            #     file: ./frontend/Dockerfile
            #     push: true
            #     tags: ghcr.io/${{ github.repository }}/frontend:latest
                
            # - name: Backend image
            #   uses: docker/build-push-action@v3
            #   with:
            #     context: ./backend
            #     file: ./backend/Dockerfile
            #     push: true
            #     tags: ghcr.io/${{ github.repository }}/backend:latest