name: CI

on:
  push:
    branches:
      - review18
  pull_request:
    branches:
      - review18
      - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Cache Docker layers
              uses: actions/cache@v3
              with:
                path: /tmp/.buildx-cache
                key: buildx

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: Setup Buildx
              uses: docker/setup-buildx-action@v3

            - name: Frontend image
              uses: docker/build-push-action@v3
              with:
                context: ./frontend
                file: ./frontend/Dockerfile
                push: true
                cache-from: type=local,src=/tmp/.buildx-cache
                cache-to: type=local,dest=/tmp/.buildx-cache
                tags: ghcr.io/film-react-nest/frontend:latest
                
            - name: Backend image
              uses: docker/build-push-action@v3
              with:
                context: ./backend
                file: ./backend/Dockerfile
                push: true
                cache-from: type=local,src=/tmp/.buildx-cache
                cache-to: type=local,dest=/tmp/.buildx-cache
                tags: ghcr.io/film-react-nest/backend:latest