name: CI

on:
  push:
    branches:
      - review18
  pull_request:
    branches:
      - review18
      - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Log in to the Docker
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: szimina
                password: Ostrov123-

            - name: Setup Buildx
              uses: docker/setup-buildx-action@v3
              
            - name: Frontend image
              uses: docker/build-push-action@v3
              with:
                context: ./frontend
                file: ./frontend/Dockerfile
                push: true
                tags: ghcr.io/szimina/frontend:latest
                
            - name: Backend image
              uses: docker/build-push-action@v3
              with:
                context: ./backend
                file: ./backend/Dockerfile
                push: true
                tags: ghcr.io/szimina/backend:latest